### ISSUE TITLE
CSS to avoid styling certain elements in an example is not working

### ISSUE THREAD

**Issue by nburwell** [patternpack/patternpack-example-theme#5]
I was surprised that out of the box when I tried to have a `<h1>` or `<h2>` in an example pattern, the DOM element was styled using CSS from the theme.  When looking in the inspector, it looks like the intention is to prevent styling elements that are in a `.library__example` element, but the selector doesn't work because the `.library__example` is not on the same element as `.markdown__body` and therefore the "not" part doesn't kick in, so the theme styles bleed in:

![image](https://cloud.githubusercontent.com/assets/372310/10955486/fe302e6c-8308-11e5-85c1-4f9066b06fee.png)

STR:
1. Used this for my headings.md file:

``````

---
title: Headings

---
## Headings
The headings below should only have the styles I provide in my SCSS, not from the pattern library styles

### Examples
<div class="library__example">
  <h1>Heading 1</h1>
  <h2>Heading 2</h2>
  <h3>Heading 3</h3>
  <h4>Heading 4</h4>
</div>

### Code
```html
<h1>Heading 1</h1>
<h2>Heading 2</h2>
<h3>Heading 3</h3>
<h4>Heading 4</h4>
``````

```

2. Go to the page: http://localhost:8888/atoms/headings.html
3. Notice that styles are not from my patterns only but from the theme SASS
```

**Comment by marcelosomers** [comment]
You're right about this one. I encountered it just recently myself.

I thought I was using the CSS :not tag properly (the whole point of the `library__example` class), but apparently it didn't work with the final version of this theme.

I'll explore some other fixes on this. I hate that there's no easy way in CSS to say "style everything inside this class UNLESS it has this class."

**Comment by marcelosomers** [comment]
So I am totally stumped on this issue. I _think_ we might need to rethink how we are styling things and would love @johngully and anyone else's input.

Here's our situation: Our theme uses a wrapper like this:

``` handlebars
<div class="markdown__body">
  {{ >body }}
</div>
```

Where `{{ > body }} spits out the contents of your markdown file. The goal is to have the`.markdown__body` give some nice default styling to our documentation.

Here's where things get messy: There's no easy way to _remove_ the styling from the "example" in our markdown file because it's nested within `.markdown__body`. Our rendered HTML is:

``` html
<div class="markdown__body">
  markdown styled content

  <div class="library__example">
    a live example that should be UNSTYLED
  </div>
</div>
```

Originally I researched using CSS' `:not` property, but it doesn't handle nesting like this too well. [Here's a Codepen with a test](http://codepen.io/marcelosomers/pen/NGLQey). You can go take a look at how I handled it, but suffice it to say, it doesn't work.

So that starts to beg the question: do we need to explore a new way to handle live code examples? Our original goal with this template was to make it really easy to document and design your code in a single file without having to do too much `<div>` gymnastics. For example, I would hate if a template had to be something like:

```
<h1 class="markdown__h1">My Header</h1>
<p class="markdown__p">My description text</p>
```

You get where I'm going...

So do we need to explore options like storing your example in a separate component file and injecting that separately? This may play well into PatternPack discussions we've had around using a template engine like Handlebars to build your component once and then be able to "inject" it into other places (e.g., an atom can easily be injected into a molecule without rewriting the code, or even injecting the live example and code snippet on the same page with the code only being written once).

This is obviously a much bigger undertaking. I'm just stumped and not seeing an "easy fix" to this problem.

**Comment by johngully** [comment]
One of the discussions that has been going on lately is about Handlebars Helpers to eliminate the duplication of the code display and code example. 

``` hbs
{{pattern-description}}
#Primary Button
The primary button should...
{{/pattern-description}}

{{pattern-code}}
 <button class="primary">primary</button>
{{/pattern-code}}
```

Following this pattern we may be able to isolate the CSS for the pattern from the CSS for the pattern library theme.  The above pattern template would render to something like this:

``` html
<div class="pattern">
  <div class="pattern__description">
    <h1>Primary Button</h1>
    <p>The primary button should...</p>
  </div>
  <div class="pattern__example">
    <button class="primary">primary</button>
  </div>
  <div class="pattern__code">
    <pre>
      <button class="primary">primary</button>
    </pre>
  </div>
  </div>
<div>
```

This structure would then allow the theme to target `.pattern .pattern__description` for any styling that should be applied to the documentation.

``` scss
.pattern {
  .pattern__description {
    margin-bottom: 25px; 
    h1: {
      font-size: 18pt;
    }
    p: {
      font-size: 14pt;
    }
  }
}
```

**Comment by marcelosomers** [comment]
I like that. How likely are we to move forward with the Handlebars version.

We'd also have to take into consideration what it might mean to a project choosing not to use Handlebars.
